compilation: main.c
	gcc main.c -o letsgo 
#i can make this whole thing work with lestgo, its the word I picked, thanks to -o (output)
#letsgo creates letsgo.exe, so maybe use main or the code's name next time because main.exe will be created automatically when u compile trough the IDE
#command prompt: make /enter/ letsgo  
#vscode: make /enter/ ./letsgo
