compilation: main.c
	gcc main.c -o letsgo 
#i can make this whole thing work with lestgo, its the word I picked, thanks to -o (output)
#main.c next to compilation is neccesary because otherwise it gets errors such as  cc: error: main.c: No such file or directory   or gcc: fatal error: no input files
#compilation: main.c
#letsgo creates letsgo.exe, so maybe use main or the code's name next time because main.exe will be created automatically when u compile trough the IDE
#per command prompt rasai make ir antra karta rasai letsgo o per vscode reik rasyt./letsgo
