compilation: main.c
	gcc main.c -o letsgo 
#i can make this whole thing work with lestgo, its the word I picked, thanks to -o (output)
#main.c next to compilation is neccesary because otherwise it gets errors
#cc: error: main.c: No such file or directory
#gcc: fatal error: no input files
#compilation: main.c
#gcc main.c -o letsgo 
#per command prompt rasai make ir antra karta rasai letsgo o per vscode reik rasyt./letsgo
